operador.py

#operador matematicos

name = "frank" # = es operador de asignacion

print(10 + 10) # operador suma +
print(10 - 5) # operador resta -
print(20 * 5) # operador multiplicacion *

# operadores de comparacion

print(10 < 10) # menor que
print(10 > 10) # mayor que
print(10 >= 10) # mayor o igual
print(10 <= 10) # menor o igual
print(10 == 10) # igual 
print(10 != 10) # diferente

# Operadores logicos

print(True and True) # AND
print(True or True) # OR
print(True is True) # IS

